// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKGJdUC43ZxsKWuLTp9Wvx2WKsw_OKPE8',
    appId: '1:1088288684771:web:9c76df500ac8af8a0363d6',
    messagingSenderId: '1088288684771',
    projectId: 'languagelearningapp-60c68',
    authDomain: 'languagelearningapp-60c68.firebaseapp.com',
    storageBucket: 'languagelearningapp-60c68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAVuPNObtK8LfPVwMfDgZjE7v9Raz9bVw',
    appId: '1:1088288684771:android:c6ed9ec27690ce320363d6',
    messagingSenderId: '1088288684771',
    projectId: 'languagelearningapp-60c68',
    storageBucket: 'languagelearningapp-60c68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALth8fvOCgdrnqtkwpRTaycIsFpKdTHTk',
    appId: '1:1088288684771:ios:8310dcfadd49e6ba0363d6',
    messagingSenderId: '1088288684771',
    projectId: 'languagelearningapp-60c68',
    storageBucket: 'languagelearningapp-60c68.firebasestorage.app',
    iosBundleId: 'com.example.lannyProgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALth8fvOCgdrnqtkwpRTaycIsFpKdTHTk',
    appId: '1:1088288684771:ios:8310dcfadd49e6ba0363d6',
    messagingSenderId: '1088288684771',
    projectId: 'languagelearningapp-60c68',
    storageBucket: 'languagelearningapp-60c68.firebasestorage.app',
    iosBundleId: 'com.example.lannyProgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKGJdUC43ZxsKWuLTp9Wvx2WKsw_OKPE8',
    appId: '1:1088288684771:web:731e48bd7696b2250363d6',
    messagingSenderId: '1088288684771',
    projectId: 'languagelearningapp-60c68',
    authDomain: 'languagelearningapp-60c68.firebaseapp.com',
    storageBucket: 'languagelearningapp-60c68.firebasestorage.app',
  );
}
